[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  Command = "yarn build"
  Functions = "functions"
  Publish = "build"
[template.environment]
  SHOPIFY_API_KEY = "Shopify API Key"
  SHOPIFY_API_SECRET = "Shopify API Secret"
  APP_URL = "Public (https) URL of the app. Must match url in Shopify app settings"
  APP_SECRET = "Secret for signing JWT"
  DATABASE_URL = "Postgres database connection string"
